"""empty message

Revision ID: 037906a8f2a3
Revises: 653c30436cc2
Create Date: 2021-01-06 11:40:51.445587

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '037906a8f2a3'
down_revision = '653c30436cc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizes', sa.Column('score', sa.Float(), nullable=True))
    op.drop_column('quizes', 'score_bla')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizes', sa.Column('score_bla', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('quizes', 'score')
    # ### end Alembic commands ###
