"""empty message

Revision ID: 5aa455d77ced
Revises: e3dc110d190f
Create Date: 2021-02-27 21:03:50.786150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aa455d77ced'
down_revision = 'e3dc110d190f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deletes', sa.Column('commentator', sa.String(length=30), nullable=True))
    op.add_column('deletes', sa.Column('terminator', sa.String(length=30), nullable=True))
    op.add_column('quizes', sa.Column('commentator', sa.String(length=30), nullable=True))
    op.add_column('quizes', sa.Column('ip', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizes', 'ip')
    op.drop_column('quizes', 'commentator')
    op.drop_column('deletes', 'terminator')
    op.drop_column('deletes', 'commentator')
    # ### end Alembic commands ###
