"""empty message

Revision ID: 653c30436cc2
Revises: bc856132cad9
Create Date: 2021-01-06 11:40:20.498582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '653c30436cc2'
down_revision = 'bc856132cad9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizes', sa.Column('score_bla', sa.Float(), nullable=True))
    op.drop_column('quizes', 'score')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizes', sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('quizes', 'score_bla')
    # ### end Alembic commands ###
