"""empty message

Revision ID: 6a29c937b692
Revises: c7ec9100faf4
Create Date: 2021-02-06 14:17:32.373363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a29c937b692'
down_revision = 'c7ec9100faf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('date', sa.DateTime(), nullable=False))
    op.add_column('accounts', sa.Column('so_secret', sa.String(length=150), nullable=True))
    op.drop_column('accounts', 'secret')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('secret', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('accounts', 'so_secret')
    op.drop_column('accounts', 'date')
    # ### end Alembic commands ###
