"""empty message

Revision ID: 928a41165630
Revises: 1341c2dae2c9
Create Date: 2021-02-28 18:40:24.420712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '928a41165630'
down_revision = '1341c2dae2c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comment', sa.String(length=500), nullable=True))
    op.add_column('comments', sa.Column('ip', sa.String(length=30), nullable=True))
    op.add_column('comments', sa.Column('name', sa.String(length=40), nullable=True))
    op.drop_column('comments', 'comments')
    op.drop_column('comments', 'commentator')
    op.add_column('quizes', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('quizes', sa.Column('finished', sa.Boolean(), nullable=True))
    op.add_column('quizes', sa.Column('terminator', sa.String(length=30), nullable=True))
    op.drop_column('quizes', 'delete_ip')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizes', sa.Column('delete_ip', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.drop_column('quizes', 'terminator')
    op.drop_column('quizes', 'finished')
    op.drop_column('quizes', 'deleted')
    op.add_column('comments', sa.Column('commentator', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('comments', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('comments', 'name')
    op.drop_column('comments', 'ip')
    op.drop_column('comments', 'comment')
    # ### end Alembic commands ###
