"""empty message

Revision ID: bc856132cad9
Revises: 94e9b0855712
Create Date: 2020-12-06 19:08:33.733671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc856132cad9'
down_revision = '94e9b0855712'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('description', sa.String(length=1000), nullable=True))
    op.drop_column('questions', 'qdescription')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('qdescription', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.drop_column('questions', 'description')
    # ### end Alembic commands ###
