"""empty message

Revision ID: bd5ad1f7a63e
Revises: fb613e0c66de
Create Date: 2020-11-24 13:08:52.799010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd5ad1f7a63e'
down_revision = 'fb613e0c66de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizes', sa.Column('questions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizes', 'questions')
    # ### end Alembic commands ###
