"""empty message

Revision ID: e3dc110d190f
Revises: 6a29c937b692
Create Date: 2021-02-27 16:20:14.645642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3dc110d190f'
down_revision = '6a29c937b692'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deletes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('participant', sa.String(length=60), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('finished', sa.Boolean(), nullable=True),
    sa.Column('questions', sa.JSON(), nullable=True),
    sa.Column('answers', sa.JSON(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('comments', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('quizes', sa.Column('comments', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizes', 'comments')
    op.drop_table('deletes')
    # ### end Alembic commands ###
