"""empty message

Revision ID: f86f2c198c17
Revises: bd5ad1f7a63e
Create Date: 2020-11-25 14:29:41.191121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f86f2c198c17'
down_revision = 'bd5ad1f7a63e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizes', sa.Column('state', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizes', 'state')
    # ### end Alembic commands ###
